% --- Goodness of fit (Clauset et al. 2009, sec 4.1, Appendix D)
% Synthetic datasets are generated by sampling the hypothesized power-law
% distribution. The Kolmogorov-Smirnov distance between the real and
% synthetic datasets are compared, and the p-value is computed as the
% fraction of synthetic distances that are larger than the empirical
% distance. Power-law distribution rejected if p ≤ 0.1 for N = 1000
% synthetic observations.
%
% Synthetic datasets are created using the method of transformation from
% random numbers r drawn from a uniform distribution on [0, 1) based on the
% method in Appendix D of Clauset et al. (2009). (see synthGen function)

function p = gofClauset(CDFtheor, dKSemp, nS, xmin, xmax)

% Synthetic datasets
N = 1000;
x = xmin:xmax;

edges = (xmin-0.5):1:xmax+0.5;
synthAvs = zeros(nS, N);
PDFsyn = zeros(length(x), N);
dKSsyn = zeros(1, N);
CDFsyn = zeros(length(x), N);
for i = 1:N
    for j = 1:nS
        r = rand;
        % Find value of CDF that's closest to CDF = 1 - r (Eq. (D.5))
        % without being less than 1 - r. Saves computation time in having
        % to perform binary search as suggested by Clauset et al. (2009).
        differ = CDFtheor - (1 - r);
        minDiff = min(differ(differ>=0));
        if isempty(minDiff)
            synthAvs(j,i) = xmax+1;
        else
            synthAvs(j,i) = find(differ == minDiff, 1) + xmin - 1;
        end
    end
    [PDFsyn(:,i), edges] = histcounts(synthAvs(:,i), edges);
    PDFsyn = PDFsyn(:,i)./sum(PDFsyn(:,i));
    for k = 1:length(x)
        CDFsyn(k,i) = sum(PDFsyn(k:end));
    end
    dKSsyn(i) = max(abs(CDFsyn(:,i) - CDFtheor));
end
fracHigher = length(find(dKSsyn >= dKSemp));
p = fracHigher/N;