% --- Goodness of fit (Clauset et al. 2009, sec 4.1, Appendix D)
% Synthetic datasets are generated by sampling the hypothesized power-law
% distribution. The Kolmogorov-Smirnov distance between the real and
% synthetic datasets are compared, and the p-value is computed as the
% fraction of synthetic distances that are larger than the empirical
% distance. Power-law distribution rejected if p ≤ 0.1 for N = 1000
% synthetic observations.
%
% Synthetic datasets are created using the method of transformation from
% random numbers r drawn from a uniform distribution on [0, 1) based on the
% method in Appendix D of Clauset et al. (2009).

function p = gofClauset(CDFtheor, dKSemp, nS, xmin, xmax)

% Synthetic datasets
if nS <= 100
    N = 5000;
else
    N = 1000;
end
x = xmin:xmax;
extra = round(CDFtheor(end)*nS);   % Include extra avalanches to make up for
                                   % ones that are sized > 60
edges = (xmin-0.5):1:xmax+0.5;
synthAvs = zeros(nS+extra, N);
synth = zeros(length(x), N);
dKSsyn = zeros(1, N);
CDFsyn = zeros(length(x), N);
for i = 1:N
    for j = 1:nS+extra
        r = rand;
        % Find value of CDF that's closest to CDF = 1 - r (Eq. (D.5))
        % without being less than 1 - r. Saves computation time in having
        % to perform binary search as suggested by Clauset et al. (2009).
        differ = CDFtheor - (1 - r);
        minDiff = min(differ(differ>=0));
        if isempty(minDiff)
            synthAvs(j,i) = 61;
        else
            synthAvs(j,i) = find(differ == minDiff, 1) + xmin - 1;
        end
    end
    [synth(:,i), edges] = histcounts(synthAvs(:,i), edges);
    PDFsyn = synth(:,i)./sum(synth(:,i));
    for j = 1:length(x)
        CDFsyn(j,i) = sum(PDFsyn(j:end));
    end
    dKSsyn(i) = max(abs(CDFsyn(:,i) - CDFtheor));
end
fracHigher = length(find(dKSsyn > dKSemp));
p = fracHigher/N;